char * greek_finder(uint16_t keycode) {
  switch (keycode) {
    case GK_A:
      return "α";
    case GK_U_A:
      return "Α";
    case GK_B:
      return "β";
    case GK_U_B:
      return "Β";
    case GK_G:
      return "γ";
    case GK_U_G:
      return "Γ";
    case GK_D:
      return "δ";
    case GK_U_D:
      return "Δ";
    case GK_E:
      return "ε";
    case GK_U_E:
      return "Ε";
    case GK_Z:
      return "ζ";
    case GK_U_Z:
      return "Ζ";
    case GK_H:
      return "η";
    case GK_U_H:
      return "Η";
    case GK_TH:
      return "θ";
    case GK_U_TH:
      return "Θ";
    case GK_I:
      return "ι";
    case GK_U_I:
      return "Ι";
    case GK_K:
      return "κ";
    case GK_U_K:
      return "Κ";
    case GK_L:
      return "λ";
    case GK_U_L:
      return "Λ";
    case GK_M:
      return "μ";
    case GK_U_M:
      return "Μ";
    case GK_N:
      return "ν";
    case GK_U_N:
      return "Ν";
    case GK_KS:
      return "ξ";
    case GK_U_KS:
      return "Ξ";
    case GK_O:
      return "ο";
    case GK_U_O:
      return "Ο";
    case GK_P:
      return "π";
    case GK_U_P:
      return "Π";
    case GK_R:
      return "ρ";
    case GK_U_R:
      return "Ρ";
    case GK_S:
      return "σ";
    case GK_U_S:
      return "Σ";
    case GK_SF:
      return "ς";
    case GK_U_SF:
      return "ς";
    case GK_T:
      return "τ";
    case GK_U_T:
      return "Τ";
    case GK_Y:
      return "υ";
    case GK_U_Y:
      return "Υ";
    case GK_PH:
      return "φ";
    case GK_U_PH:
      return "Φ";
    case GK_KH:
      return "χ";
    case GK_U_KH:
      return "Χ";
    case GK_PS:
      return "ψ";
    case GK_U_PS:
      return "Ψ";
    case GK_OO:
      return "ω";
    case GK_U_OO:
      return "Ω";
    case GK_W:
      return "ϝ";
    case GK_U_W:
      return "Ϝ";
    case GK_HH:
      return "";
    case GK_U_HH:
      return "ͱ";
    default:
      return "";
  }
}
