char * russian_finder(uint16_t keycode) {
  switch (keycode) {
    case R_A:
      return "а";
    case R_U_A:
      return "А";
    case R_B:
      return "б";
    case R_U_B:
      return "Б";
    case R_V:
      return "в";
    case R_U_V:
      return "В";
    case R_G:
      return "г";
    case R_U_G:
      return "Г";
    case R_D:
      return "д";
    case R_U_D:
      return "Д";
    case R_JE:
      return "е";
    case R_U_JE:
      return "Е";
    case R_E:
      return "э";
    case R_U_E:
      return "Э";
    case R_ZH:
      return "ж";
    case R_U_ZH:
      return "Ж";
    case R_Z:
      return "з";
    case R_U_Z:
      return "З";
    case R_I:
      return "и";
    case R_U_I:
      return "И";
    case R_K:
      return "к";
    case R_U_K:
      return "К";
    case R_L:
      return "л";
    case R_U_L:
      return "Л";
    case R_M:
      return "м";
    case R_U_M:
      return "М";
    case R_N:
      return "н";
    case R_U_N:
      return "Н";
    case R_O:
      return "о";
    case R_U_O:
      return "О";
    case R_P:
      return "п";
    case R_U_P:
      return "П";
    case R_R:
      return "р";
    case R_U_R:
      return "Р";
    case R_S:
      return "с";
    case R_U_S:
      return "С";
    case R_T:
      return "т";
    case R_U_T:
      return "Т";
    case R_U:
      return "у";
    case R_U_U:
      return "У";
    case R_F:
      return "ф";
    case R_U_F:
      return "Ф";
    case R_H:
      return "х";
    case R_U_H:
      return "Х";
    case R_C:
      return "ц";
    case R_U_C:
      return "Ц";
    case R_CH:
      return "ч";
    case R_U_CH:
      return "Ч";
    case R_SH:
      return "ш";
    case R_U_SH:
      return "Ш";
    case R_SHCH:
      return "щ";
    case R_U_SHCH:
      return "Щ";
    case R_HA:
      return "ъ";
    case R_U_HA:
      return "Ъ";
    case R_Y:
      return "ы";
    case R_U_Y:
      return "Ы";
    case R_SO:
      return "ь";
    case R_U_SO:
      return "Ь";
    case R_YU:
      return "ю";
    case R_U_YU:
      return "Ю";
    case R_YA:
      return "я";
    case R_U_YA:
      return "Я";
    case R_IA:
      return "ꙗ";
    case R_U_IA:
      return "Ꙗ";
    case R_IE:
      return "ѥ";
    case R_U_IE:
      return "Ѥ";
    case R_EN:
      return "ѧ";
    case R_U_EN:
      return "Ѧ";
    case R_ON:
      return "ѫ";
    case R_U_ON:
      return "Ѫ";
    case R_IEN:
      return "ѩ";
    case R_U_IEN:
      return "Ѩ";
    case R_ION:
      return "ѭ";
    case R_U_ION:
      return "Ѭ";
    default:
      return "";
  }
}
